//*****************************************************************************
//*****************************************************************************
//  FILENAME: CS_PIN.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: CS_PIN User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef CS_PIN_INCLUDE
#define CS_PIN_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  CS_PIN_Stop
#pragma fastcall16  CS_PIN_Start
#pragma fastcall16  CS_PIN_On
#pragma fastcall16  CS_PIN_Off
#pragma fastcall16  CS_PIN_Switch
#pragma fastcall16  CS_PIN_Invert
#pragma fastcall16  CS_PIN_GetState


//-------------------------------------------------
// Constants for CS_PIN API's.
//-------------------------------------------------
//
#define  CS_PIN_ON   1
#define  CS_PIN_OFF  0

//-------------------------------------------------
// Prototypes of the CS_PIN API.
//-------------------------------------------------
extern void  CS_PIN_Start(void);                                     
extern void  CS_PIN_Stop(void);                                      
extern void  CS_PIN_On(void);                                      
extern void  CS_PIN_Off(void);                                      
extern void  CS_PIN_Switch(BYTE bSwitch);
extern void  CS_PIN_Invert(void);                                         
extern BYTE  CS_PIN_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
