//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_1_4.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_1_4 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_1_4_INCLUDE
#define LED_1_4_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_1_4_Stop
#pragma fastcall16  LED_1_4_Start
#pragma fastcall16  LED_1_4_On
#pragma fastcall16  LED_1_4_Off
#pragma fastcall16  LED_1_4_Switch
#pragma fastcall16  LED_1_4_Invert
#pragma fastcall16  LED_1_4_GetState


//-------------------------------------------------
// Constants for LED_1_4 API's.
//-------------------------------------------------
//
#define  LED_1_4_ON   1
#define  LED_1_4_OFF  0

//-------------------------------------------------
// Prototypes of the LED_1_4 API.
//-------------------------------------------------
extern void  LED_1_4_Start(void);                                     
extern void  LED_1_4_Stop(void);                                      
extern void  LED_1_4_On(void);                                      
extern void  LED_1_4_Off(void);                                      
extern void  LED_1_4_Switch(BYTE bSwitch);
extern void  LED_1_4_Invert(void);                                         
extern BYTE  LED_1_4_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
