//*****************************************************************************
//*****************************************************************************
//  FILENAME: RST.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: RST User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef RST_INCLUDE
#define RST_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  RST_Stop
#pragma fastcall16  RST_Start
#pragma fastcall16  RST_On
#pragma fastcall16  RST_Off
#pragma fastcall16  RST_Switch
#pragma fastcall16  RST_Invert
#pragma fastcall16  RST_GetState


//-------------------------------------------------
// Constants for RST API's.
//-------------------------------------------------
//
#define  RST_ON   1
#define  RST_OFF  0

//-------------------------------------------------
// Prototypes of the RST API.
//-------------------------------------------------
extern void  RST_Start(void);                                     
extern void  RST_Stop(void);                                      
extern void  RST_On(void);                                      
extern void  RST_Off(void);                                      
extern void  RST_Switch(BYTE bSwitch);
extern void  RST_Invert(void);                                         
extern BYTE  RST_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
