/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "CH0_OUT.h"
#include "CH1_OUT.h"
#include "CH2_OUT.h"
#include "CH3_OUT.h"
#include "CH4_OUT.h"
#include "CH5_OUT.h"
#include "CS_PIN.h"
#include "E2PROM_1.h"
#include "LED_1.h"
#include "PWM16_1.h"
#include "RST.h"
#include "SPIM_1.h"
#include "SleepTimer_1.h"
#include "Timer8_1.h"

#endif
