/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
/*
*   PSoCGPIOINT.h
*   Data: 04 June, 2002
*   Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
*
*  This file is generated by the Device Editor on Application Generation.
*  It contains equates that are useful in writing code relating to GPIO
*  related values.
*  
*  DO NOT EDIT THIS FILE MANUALLY, AS IT IS OVERWRITTEN!!!
*  Edits to this file will not be preserved.
*/
// CY_IRQPin address and mask defines
#pragma	ioport	CY_IRQPin_Data_ADDR:	0x0
BYTE			CY_IRQPin_Data_ADDR;
#pragma	ioport	CY_IRQPin_DriveMode_0_ADDR:	0x100
BYTE			CY_IRQPin_DriveMode_0_ADDR;
#pragma	ioport	CY_IRQPin_DriveMode_1_ADDR:	0x101
BYTE			CY_IRQPin_DriveMode_1_ADDR;
#pragma	ioport	CY_IRQPin_DriveMode_2_ADDR:	0x3
BYTE			CY_IRQPin_DriveMode_2_ADDR;
#pragma	ioport	CY_IRQPin_GlobalSelect_ADDR:	0x2
BYTE			CY_IRQPin_GlobalSelect_ADDR;
#pragma	ioport	CY_IRQPin_IntCtrl_0_ADDR:	0x102
BYTE			CY_IRQPin_IntCtrl_0_ADDR;
#pragma	ioport	CY_IRQPin_IntCtrl_1_ADDR:	0x103
BYTE			CY_IRQPin_IntCtrl_1_ADDR;
#pragma	ioport	CY_IRQPin_IntEn_ADDR:	0x1
BYTE			CY_IRQPin_IntEn_ADDR;
#define CY_IRQPin_MASK 0x40
#pragma	ioport	CY_IRQPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			CY_IRQPin_MUXBusCtrl_ADDR;
// CY_IRQPin Shadow defines
//   CY_IRQPin_DataShadow define
extern unsigned char Port_0_Data_SHADE;
#define CY_IRQPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// MISOPin address and mask defines
#pragma	ioport	MISOPin_Data_ADDR:	0x0
BYTE			MISOPin_Data_ADDR;
#pragma	ioport	MISOPin_DriveMode_0_ADDR:	0x100
BYTE			MISOPin_DriveMode_0_ADDR;
#pragma	ioport	MISOPin_DriveMode_1_ADDR:	0x101
BYTE			MISOPin_DriveMode_1_ADDR;
#pragma	ioport	MISOPin_DriveMode_2_ADDR:	0x3
BYTE			MISOPin_DriveMode_2_ADDR;
#pragma	ioport	MISOPin_GlobalSelect_ADDR:	0x2
BYTE			MISOPin_GlobalSelect_ADDR;
#pragma	ioport	MISOPin_IntCtrl_0_ADDR:	0x102
BYTE			MISOPin_IntCtrl_0_ADDR;
#pragma	ioport	MISOPin_IntCtrl_1_ADDR:	0x103
BYTE			MISOPin_IntCtrl_1_ADDR;
#pragma	ioport	MISOPin_IntEn_ADDR:	0x1
BYTE			MISOPin_IntEn_ADDR;
#define MISOPin_MASK 0x1
#pragma	ioport	MISOPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			MISOPin_MUXBusCtrl_ADDR;
// MISOPin Shadow defines
//   MISOPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define MISOPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// SCK_Pin address and mask defines
#pragma	ioport	SCK_Pin_Data_ADDR:	0x0
BYTE			SCK_Pin_Data_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_0_ADDR:	0x100
BYTE			SCK_Pin_DriveMode_0_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_1_ADDR:	0x101
BYTE			SCK_Pin_DriveMode_1_ADDR;
#pragma	ioport	SCK_Pin_DriveMode_2_ADDR:	0x3
BYTE			SCK_Pin_DriveMode_2_ADDR;
#pragma	ioport	SCK_Pin_GlobalSelect_ADDR:	0x2
BYTE			SCK_Pin_GlobalSelect_ADDR;
#pragma	ioport	SCK_Pin_IntCtrl_0_ADDR:	0x102
BYTE			SCK_Pin_IntCtrl_0_ADDR;
#pragma	ioport	SCK_Pin_IntCtrl_1_ADDR:	0x103
BYTE			SCK_Pin_IntCtrl_1_ADDR;
#pragma	ioport	SCK_Pin_IntEn_ADDR:	0x1
BYTE			SCK_Pin_IntEn_ADDR;
#define SCK_Pin_MASK 0x8
#pragma	ioport	SCK_Pin_MUXBusCtrl_ADDR:	0x1d8
BYTE			SCK_Pin_MUXBusCtrl_ADDR;
// SCK_Pin Shadow defines
//   SCK_Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define SCK_Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// RSTPin address and mask defines
#pragma	ioport	RSTPin_Data_ADDR:	0x0
BYTE			RSTPin_Data_ADDR;
#pragma	ioport	RSTPin_DriveMode_0_ADDR:	0x100
BYTE			RSTPin_DriveMode_0_ADDR;
#pragma	ioport	RSTPin_DriveMode_1_ADDR:	0x101
BYTE			RSTPin_DriveMode_1_ADDR;
#pragma	ioport	RSTPin_DriveMode_2_ADDR:	0x3
BYTE			RSTPin_DriveMode_2_ADDR;
#pragma	ioport	RSTPin_GlobalSelect_ADDR:	0x2
BYTE			RSTPin_GlobalSelect_ADDR;
#pragma	ioport	RSTPin_IntCtrl_0_ADDR:	0x102
BYTE			RSTPin_IntCtrl_0_ADDR;
#pragma	ioport	RSTPin_IntCtrl_1_ADDR:	0x103
BYTE			RSTPin_IntCtrl_1_ADDR;
#pragma	ioport	RSTPin_IntEn_ADDR:	0x1
BYTE			RSTPin_IntEn_ADDR;
#define RSTPin_MASK 0x10
#pragma	ioport	RSTPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			RSTPin_MUXBusCtrl_ADDR;
// RSTPin Shadow defines
//   RSTPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define RSTPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// MOSI_Pin address and mask defines
#pragma	ioport	MOSI_Pin_Data_ADDR:	0x0
BYTE			MOSI_Pin_Data_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_0_ADDR:	0x100
BYTE			MOSI_Pin_DriveMode_0_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_1_ADDR:	0x101
BYTE			MOSI_Pin_DriveMode_1_ADDR;
#pragma	ioport	MOSI_Pin_DriveMode_2_ADDR:	0x3
BYTE			MOSI_Pin_DriveMode_2_ADDR;
#pragma	ioport	MOSI_Pin_GlobalSelect_ADDR:	0x2
BYTE			MOSI_Pin_GlobalSelect_ADDR;
#pragma	ioport	MOSI_Pin_IntCtrl_0_ADDR:	0x102
BYTE			MOSI_Pin_IntCtrl_0_ADDR;
#pragma	ioport	MOSI_Pin_IntCtrl_1_ADDR:	0x103
BYTE			MOSI_Pin_IntCtrl_1_ADDR;
#pragma	ioport	MOSI_Pin_IntEn_ADDR:	0x1
BYTE			MOSI_Pin_IntEn_ADDR;
#define MOSI_Pin_MASK 0x20
#pragma	ioport	MOSI_Pin_MUXBusCtrl_ADDR:	0x1d8
BYTE			MOSI_Pin_MUXBusCtrl_ADDR;
// MOSI_Pin Shadow defines
//   MOSI_Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define MOSI_Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CS_PINPin address and mask defines
#pragma	ioport	CS_PINPin_Data_ADDR:	0x0
BYTE			CS_PINPin_Data_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_0_ADDR:	0x100
BYTE			CS_PINPin_DriveMode_0_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_1_ADDR:	0x101
BYTE			CS_PINPin_DriveMode_1_ADDR;
#pragma	ioport	CS_PINPin_DriveMode_2_ADDR:	0x3
BYTE			CS_PINPin_DriveMode_2_ADDR;
#pragma	ioport	CS_PINPin_GlobalSelect_ADDR:	0x2
BYTE			CS_PINPin_GlobalSelect_ADDR;
#pragma	ioport	CS_PINPin_IntCtrl_0_ADDR:	0x102
BYTE			CS_PINPin_IntCtrl_0_ADDR;
#pragma	ioport	CS_PINPin_IntCtrl_1_ADDR:	0x103
BYTE			CS_PINPin_IntCtrl_1_ADDR;
#pragma	ioport	CS_PINPin_IntEn_ADDR:	0x1
BYTE			CS_PINPin_IntEn_ADDR;
#define CS_PINPin_MASK 0x80
#pragma	ioport	CS_PINPin_MUXBusCtrl_ADDR:	0x1d8
BYTE			CS_PINPin_MUXBusCtrl_ADDR;
// CS_PINPin Shadow defines
//   CS_PINPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define CS_PINPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// CH3_OUTPin address and mask defines
#pragma	ioport	CH3_OUTPin_Data_ADDR:	0x4
BYTE			CH3_OUTPin_Data_ADDR;
#pragma	ioport	CH3_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH3_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH3_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH3_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH3_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH3_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH3_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH3_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH3_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH3_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH3_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH3_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH3_OUTPin_IntEn_ADDR:	0x5
BYTE			CH3_OUTPin_IntEn_ADDR;
#define CH3_OUTPin_MASK 0x1
#pragma	ioport	CH3_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH3_OUTPin_MUXBusCtrl_ADDR;
// CH3_OUTPin Shadow defines
//   CH3_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH3_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CH1_OUTPin address and mask defines
#pragma	ioport	CH1_OUTPin_Data_ADDR:	0x4
BYTE			CH1_OUTPin_Data_ADDR;
#pragma	ioport	CH1_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH1_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH1_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH1_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH1_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH1_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH1_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH1_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH1_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH1_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH1_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH1_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH1_OUTPin_IntEn_ADDR:	0x5
BYTE			CH1_OUTPin_IntEn_ADDR;
#define CH1_OUTPin_MASK 0x2
#pragma	ioport	CH1_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH1_OUTPin_MUXBusCtrl_ADDR;
// CH1_OUTPin Shadow defines
//   CH1_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH1_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CH4_OUTPin address and mask defines
#pragma	ioport	CH4_OUTPin_Data_ADDR:	0x4
BYTE			CH4_OUTPin_Data_ADDR;
#pragma	ioport	CH4_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH4_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH4_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH4_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH4_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH4_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH4_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH4_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH4_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH4_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH4_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH4_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH4_OUTPin_IntEn_ADDR:	0x5
BYTE			CH4_OUTPin_IntEn_ADDR;
#define CH4_OUTPin_MASK 0x10
#pragma	ioport	CH4_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH4_OUTPin_MUXBusCtrl_ADDR;
// CH4_OUTPin Shadow defines
//   CH4_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH4_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CH2_OUTPin address and mask defines
#pragma	ioport	CH2_OUTPin_Data_ADDR:	0x4
BYTE			CH2_OUTPin_Data_ADDR;
#pragma	ioport	CH2_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH2_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH2_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH2_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH2_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH2_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH2_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH2_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH2_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH2_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH2_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH2_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH2_OUTPin_IntEn_ADDR:	0x5
BYTE			CH2_OUTPin_IntEn_ADDR;
#define CH2_OUTPin_MASK 0x20
#pragma	ioport	CH2_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH2_OUTPin_MUXBusCtrl_ADDR;
// CH2_OUTPin Shadow defines
//   CH2_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH2_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CH5_OUTPin address and mask defines
#pragma	ioport	CH5_OUTPin_Data_ADDR:	0x4
BYTE			CH5_OUTPin_Data_ADDR;
#pragma	ioport	CH5_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH5_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH5_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH5_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH5_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH5_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH5_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH5_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH5_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH5_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH5_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH5_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH5_OUTPin_IntEn_ADDR:	0x5
BYTE			CH5_OUTPin_IntEn_ADDR;
#define CH5_OUTPin_MASK 0x40
#pragma	ioport	CH5_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH5_OUTPin_MUXBusCtrl_ADDR;
// CH5_OUTPin Shadow defines
//   CH5_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH5_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CH0_OUTPin address and mask defines
#pragma	ioport	CH0_OUTPin_Data_ADDR:	0x4
BYTE			CH0_OUTPin_Data_ADDR;
#pragma	ioport	CH0_OUTPin_DriveMode_0_ADDR:	0x104
BYTE			CH0_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	CH0_OUTPin_DriveMode_1_ADDR:	0x105
BYTE			CH0_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	CH0_OUTPin_DriveMode_2_ADDR:	0x7
BYTE			CH0_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	CH0_OUTPin_GlobalSelect_ADDR:	0x6
BYTE			CH0_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	CH0_OUTPin_IntCtrl_0_ADDR:	0x106
BYTE			CH0_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	CH0_OUTPin_IntCtrl_1_ADDR:	0x107
BYTE			CH0_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	CH0_OUTPin_IntEn_ADDR:	0x5
BYTE			CH0_OUTPin_IntEn_ADDR;
#define CH0_OUTPin_MASK 0x80
#pragma	ioport	CH0_OUTPin_MUXBusCtrl_ADDR:	0x1d9
BYTE			CH0_OUTPin_MUXBusCtrl_ADDR;
// CH0_OUTPin Shadow defines
//   CH0_OUTPin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CH0_OUTPin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0xc
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x10c
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x10d
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0xf
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0xe
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x10e
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x10f
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0xd
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x1
#pragma	ioport	LED_1Pin_MUXBusCtrl_ADDR:	0x1db
BYTE			LED_1Pin_MUXBusCtrl_ADDR;
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
// Bind_Port address and mask defines
#pragma	ioport	Bind_Port_Data_ADDR:	0xc
BYTE			Bind_Port_Data_ADDR;
#pragma	ioport	Bind_Port_DriveMode_0_ADDR:	0x10c
BYTE			Bind_Port_DriveMode_0_ADDR;
#pragma	ioport	Bind_Port_DriveMode_1_ADDR:	0x10d
BYTE			Bind_Port_DriveMode_1_ADDR;
#pragma	ioport	Bind_Port_DriveMode_2_ADDR:	0xf
BYTE			Bind_Port_DriveMode_2_ADDR;
#pragma	ioport	Bind_Port_GlobalSelect_ADDR:	0xe
BYTE			Bind_Port_GlobalSelect_ADDR;
#pragma	ioport	Bind_Port_IntCtrl_0_ADDR:	0x10e
BYTE			Bind_Port_IntCtrl_0_ADDR;
#pragma	ioport	Bind_Port_IntCtrl_1_ADDR:	0x10f
BYTE			Bind_Port_IntCtrl_1_ADDR;
#pragma	ioport	Bind_Port_IntEn_ADDR:	0xd
BYTE			Bind_Port_IntEn_ADDR;
#define Bind_Port_MASK 0x4
#pragma	ioport	Bind_Port_MUXBusCtrl_ADDR:	0x1db
BYTE			Bind_Port_MUXBusCtrl_ADDR;
// Bind_Port Shadow defines
//   Bind_Port_DataShadow define
extern BYTE Port_3_Data_SHADE;
#define Bind_Port_DataShadow (*(unsigned char*)&Port_3_Data_SHADE)
