//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_1_7.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_1_7 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_1_7_INCLUDE
#define LED_1_7_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_1_7_Stop
#pragma fastcall16  LED_1_7_Start
#pragma fastcall16  LED_1_7_On
#pragma fastcall16  LED_1_7_Off
#pragma fastcall16  LED_1_7_Switch
#pragma fastcall16  LED_1_7_Invert
#pragma fastcall16  LED_1_7_GetState


//-------------------------------------------------
// Constants for LED_1_7 API's.
//-------------------------------------------------
//
#define  LED_1_7_ON   1
#define  LED_1_7_OFF  0

//-------------------------------------------------
// Prototypes of the LED_1_7 API.
//-------------------------------------------------
extern void  LED_1_7_Start(void);                                     
extern void  LED_1_7_Stop(void);                                      
extern void  LED_1_7_On(void);                                      
extern void  LED_1_7_Off(void);                                      
extern void  LED_1_7_Switch(BYTE bSwitch);
extern void  LED_1_7_Invert(void);                                         
extern BYTE  LED_1_7_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
