//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_1_0.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_1_0 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_1_0_INCLUDE
#define LED_1_0_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_1_0_Stop
#pragma fastcall16  LED_1_0_Start
#pragma fastcall16  LED_1_0_On
#pragma fastcall16  LED_1_0_Off
#pragma fastcall16  LED_1_0_Switch
#pragma fastcall16  LED_1_0_Invert
#pragma fastcall16  LED_1_0_GetState


//-------------------------------------------------
// Constants for LED_1_0 API's.
//-------------------------------------------------
//
#define  LED_1_0_ON   1
#define  LED_1_0_OFF  0

//-------------------------------------------------
// Prototypes of the LED_1_0 API.
//-------------------------------------------------
extern void  LED_1_0_Start(void);                                     
extern void  LED_1_0_Stop(void);                                      
extern void  LED_1_0_On(void);                                      
extern void  LED_1_0_Off(void);                                      
extern void  LED_1_0_Switch(BYTE bSwitch);
extern void  LED_1_0_Invert(void);                                         
extern BYTE  LED_1_0_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
