//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_1_5.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: LED_1_5 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_1_5_INCLUDE
#define LED_1_5_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_1_5_Stop
#pragma fastcall16  LED_1_5_Start
#pragma fastcall16  LED_1_5_On
#pragma fastcall16  LED_1_5_Off
#pragma fastcall16  LED_1_5_Switch
#pragma fastcall16  LED_1_5_Invert
#pragma fastcall16  LED_1_5_GetState


//-------------------------------------------------
// Constants for LED_1_5 API's.
//-------------------------------------------------
//
#define  LED_1_5_ON   1
#define  LED_1_5_OFF  0

//-------------------------------------------------
// Prototypes of the LED_1_5 API.
//-------------------------------------------------
extern void  LED_1_5_Start(void);                                     
extern void  LED_1_5_Stop(void);                                      
extern void  LED_1_5_On(void);                                      
extern void  LED_1_5_Off(void);                                      
extern void  LED_1_5_Switch(BYTE bSwitch);
extern void  LED_1_5_Invert(void);                                         
extern BYTE  LED_1_5_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
